from datetime import datetime
from typing import Optional, Protocol

from . import models


class RelationalRepositoryInterface(Protocol):
    # ── Usuarios ──────────────────────────────────────────────
    async def get_usuario_by_email(self, email: str) -> Optional[models.Usuario]: ...
    async def create_usuario(self, email: str, nombre: str, hash_password: str, rol: str, admin_email: Optional[str] = None, telefono: Optional[str] = None) -> models.Usuario: ...
    async def list_usuarios(self, admin_email: Optional[str] = None) -> list[models.Usuario]: ...
    async def update_usuario(self, email: str, **kwargs) -> Optional[models.Usuario]: ...
    async def delete_usuario(self, email: str) -> bool: ...

    # ── Campos ────────────────────────────────────────────────
    async def get_campo_by_nombre(self, nombre: str) -> Optional[models.Campo]: ...
    async def create_campo(self, nombre: str, coordenadas: str, admin_email: str, descripcion: Optional[str] = None) -> models.Campo: ...
    async def list_campos(self, admin_email: Optional[str] = None) -> list[models.Campo]: ...
    async def update_campo(self, nombre: str, **kwargs) -> Optional[models.Campo]: ...
    async def delete_campo(self, nombre: str) -> bool: ...

    # ── Parcelas ──────────────────────────────────────────────
    async def get_parcela_by_nombre(self, nombre: str, nombre_campo: str) -> Optional[models.Parcela]: ...
    async def create_parcela(self, nombre: str, coordenadas: str, nombre_campo: str, admin_email: str, descripcion: Optional[str] = None, nombre_cultivo: Optional[str] = None, variedad: Optional[str] = None) -> models.Parcela: ...
    async def list_parcelas_by_campo(self, nombre_campo: str) -> list[models.Parcela]: ...
    async def update_parcela(self, nombre: str, nombre_campo: str, **kwargs) -> Optional[models.Parcela]: ...
    async def delete_parcela(self, nombre: str, nombre_campo: str) -> bool: ...

    # ── Cultivos ──────────────────────────────────────────────
    async def create_cultivo(self, nombre: str, variedad: str, admin_email: str) -> models.Cultivo: ...
    async def list_cultivos(self, admin_email: Optional[str] = None) -> list[models.Cultivo]: ...
    async def get_cultivo_by_nombre(self, nombre: str, variedad: str) -> Optional[models.Cultivo]: ...
    async def delete_cultivo(self, nombre: str, variedad: str) -> bool: ...

    # ── Reglas ────────────────────────────────────────────────
    async def create_regla(self, nombre: str, metrica: str, operador: str, valor: float, admin_email: str, descripcion: Optional[str] = None, campos_asignados: Optional[list[str]] = None) -> models.Regla: ...
    async def get_regla_by_id(self, regla_id) -> Optional[models.Regla]: ...
    async def list_reglas(self, admin_email: Optional[str] = None) -> list[models.Regla]: ...
    async def list_reglas_by_campo(self, nombre_campo: str) -> list[models.Regla]: ...
    async def update_regla(self, regla_id, **kwargs) -> Optional[models.Regla]: ...
    async def delete_regla(self, regla_id) -> bool: ...

    # ── Sensores ──────────────────────────────────────────────
    async def create_sensor(self, device_id: str, nombre_campo: str, nombre_parcela: str, tipo: str, admin_email: str, activo: bool = True) -> models.Sensor: ...
    async def get_sensor(self, device_id: str) -> Optional[models.Sensor]: ...
    async def list_sensores(self, admin_email: Optional[str] = None) -> list[models.Sensor]: ...
    async def update_sensor(self, device_id: str, **kwargs) -> Optional[models.Sensor]: ...
    async def delete_sensor(self, device_id: str) -> bool: ...

    # ── Alertas ───────────────────────────────────────────────
    async def create_alerta(self, fecha_emision: datetime, mensaje: str, nombre_parcela: str, email_usuario: Optional[str] = None) -> models.Alerta: ...
    async def list_alertas_by_usuario(self, email_usuario: str, page: int = 1, limit: int = 20) -> tuple[list[models.Alerta], int]: ...
    async def list_alertas_by_parcela(self, nombre_parcela: str, page: int = 1, limit: int = 20) -> tuple[list[models.Alerta], int]: ...

    # ── Predicciones ──────────────────────────────────────────
    async def create_prediccion(self, fecha_emision: datetime, resultado: str, fecha_ini: datetime, fecha_fin: datetime, nombre_campo: str, nombre_regla: Optional[str] = None) -> models.Prediccion: ...
    async def list_predicciones_by_campo(self, nombre_campo: str, page: int = 1, limit: int = 20) -> tuple[list[models.Prediccion], int]: ...

    # ── Imágenes Satelitales ──────────────────────────────────
    async def create_imagen_satelital(self, id_imagen: str, fecha_captura: datetime, proveedor: str) -> models.ImagenSatelital: ...
    async def list_imagenes(self) -> list[models.ImagenSatelital]: ...
    async def asociar_imagen_a_parcela(self, id_imagen: str, nombre_parcela: str, nombre_campo: str = "", ndvi: Optional[float] = None, ndmi: Optional[float] = None) -> models.ParcelaImagenSatelital: ...
    async def get_imagenes_by_parcela(self, nombre_parcela: str, nombre_campo: str = "", limit: int = 50) -> list[models.ParcelaImagenSatelital]: ...

    # ── Ejecución Batch ───────────────────────────────────────
    async def create_ejecucion_batch(self, fecha_ini: datetime, estado: str = "EN_CURSO") -> models.EjecucionBatch: ...
    async def finalizar_ejecucion_batch(self, fecha_ini: datetime, estado: str, fecha_fin: datetime) -> Optional[models.EjecucionBatch]: ...
    async def list_ejecuciones_batch(self) -> list[models.EjecucionBatch]: ...
